/* a  */
SELECT BRANCHNUM
FROM BRANCH
WHERE BRANCHNUM not in (
SELECT BRANCHNUM
FROM CUSTOMER,BRANCH
WHERE BRANCH.BRANCHNUM=CUSTOMER.CUSTBRANCHNUM)

/*b*/
SELECT EMPLOYEE.BRANCHNUM 
FROM BRANCH ,EMPLOYEE 
WHERE BRANCH.BRANCHNUM<>EMPLOYEE.BRANCHNUM

/*  C*/
SELECT EMPFNAME,EMPNAME
FROM EMPLOYEE,LOAN
WHERE LOANAMOUNT=(SELECT MAX(LOANAMOUNT)FROM LOAN); 

/*   d*/
SELECT FNAME,LNAME
FROM CUSTOMER,LOAN
WHERE LOANAMOUNT=(SELECT MAX(LOANAMOUNT)FROM LOAN); 

/*  e*/
SELECT FNAME,LNAME 
FROM CUSTOMER,LOAN
where CUSTOMER.SSN<>LOAN.SSN;

/* f*/
SELECT CUSTOMER.SSN, CUSTOMER.CUSTBRANCHNUM, CUSTOMER.FNAME, CUSTOMER.LNAME, CUSTOMER.COUNTRY, CUSTOMER.ZIPCODE, CUSTOMER.STREET, CUSTOMER.BUILDINGNUM , COUNTCUSTOMER.SSN, CUSTOMER.CUSTBRANCHNUM, CUSTOMER.FNAME, CUSTOMER.LNAME, CUSTOMER.COUNTRY, CUSTOMER.ZIPCODE, CUSTOMER.STREET, CUSTOMER.BUILDINGNUM ,(EMPLOYEE.EMPID)
FROM CUSTOMER, EMPLOYEE, SERVE
WHERE(CUSTOMER.SSN = SERVE.SSN AND
EMPLOYEE.EMPID = SERVE.EMPID)
GROUP BY CUSTOMER.SSN, CUSTOMER.CUSTBRANCHNUM, CUSTOMER.FNAME, CUSTOMER.LNAME, CUSTOMER.COUNTRY, CUSTOMER.ZIPCODE, CUSTOMER.STREET, CUSTOMER.BUILDINGNUM , COUNTCUSTOMER.SSN, CUSTOMER.CUSTBRANCHNUM, CUSTOMER.FNAME, CUSTOMER.LNAME, CUSTOMER.COUNTRY, CUSTOMER.ZIPCODE, CUSTOMER.STREET, CUSTOMER.BUILDINGNUM ,(EMPLOYEE.EMPID)
